[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/data/coze/run/supervisord.pid
childlogdir=/data/coze/logs

[program:mariadb]
priority=10
directory=/app
command=/opt/coze-hfs/bin/run-mariadb.sh
user=user
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:redis]
priority=20
command=/usr/bin/redis-server /opt/coze-hfs/conf/redis.conf
user=user
autostart=true
autorestart=true
startsecs=2
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:nats]
priority=30
command=/usr/bin/nats-server -c /opt/coze-hfs/conf/nats-server.conf
user=user
autostart=true
autorestart=true
startsecs=2
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:minio]
priority=35
command=/opt/coze-hfs/bin/run-minio.sh
user=user
autostart=true
autorestart=false
startsecs=1
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:minio-init]
priority=36
command=/opt/coze-hfs/bin/init-minio.sh
user=user
autostart=true
autorestart=false
startsecs=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:etcd]
priority=40
command=/opt/coze-hfs/bin/run-etcd.sh
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:elasticsearch]
priority=45
command=/opt/coze-hfs/bin/run-elasticsearch.sh
autostart=true
autorestart=true
startsecs=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:milvus]
priority=50
directory=/milvus
command=/opt/coze-hfs/bin/run-milvus.sh
autostart=true
autorestart=true
startsecs=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:coze-server]
priority=60
directory=/app
command=/opt/coze-hfs/bin/run-coze-server.sh
user=user
autostart=true
autorestart=true
startsecs=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:ops-service]
priority=65
directory=/app
command=/opt/coze-hfs/bin/run-ops-service.sh
user=user
autostart=true
autorestart=true
startsecs=2
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:nginx]
priority=70
command=/usr/sbin/nginx -c /opt/coze-hfs/conf/nginx.conf -g 'daemon off;'
user=user
autostart=true
autorestart=true
startsecs=2
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
